#atasources:
# - name: Prometheus
#   access: proxy
#   type: prometheus
#   url: http://prometheus:9090
#   user: admin
#   isDefault: true

datasources:
  - name: 'prometheus'
    type: 'prometheus'
    access: 'proxy'
    org_id: 1
    url: 'http://prometheus:9090'
    is_default: true
    version: 1
    editable: true