global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'microservices app'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend-app:8081']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend-app:8081','prometheus:9090']
        labels:
          application: 'microservices app'